version: "3.3"

services:
  api:
    build: .
    container_name: api
    ports:
      - "3333:3333"

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    restart: always
    ports:
      - "9000:9000"
    links:
      - api
    depends_on:
      - api

  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
    links:
      - api
    depends_on:
      - api
